### ISSUE TITLE
Make osscameroon April 2023 update video

### ISSUE THREAD

**Issue by elhmn** [osscameroon/roadmap#4]
We need to make a video that explain our progress at osscameroon.
Essentially everything we have built during the beginning of the year should be presented
in a short video of 5 mins maximum

**Comment by tericcabrel** [comment]
I agree

**Comment by elhmn** [comment]
I don't think we will do this anymore

**Comment by elhmn** [comment]
> I agree

Oops I closed it, but yeah we can either do a blog post or a youtube video

**Comment by tericcabrel** [comment]
Yess, a blog post is more reasonable

**Comment by rakici** [comment]
This never happened
